// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi3PskP4rkmjaETTu0hipcILh27wWhsgA',
    appId: '1:332757779499:web:8863064d105be9351c166e',
    messagingSenderId: '332757779499',
    projectId: 'smartspace-66555',
    authDomain: 'smartspace-66555.firebaseapp.com',
    storageBucket: 'smartspace-66555.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANkg7AUJYSqRaWY2EIhw7RmmNJiAl-92k',
    appId: '1:332757779499:android:e6627484750110f71c166e',
    messagingSenderId: '332757779499',
    projectId: 'smartspace-66555',
    storageBucket: 'smartspace-66555.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9vayT4hvqv2fky7iT8NC0nUcJzuwxU7w',
    appId: '1:332757779499:ios:682ae09c7c5646cb1c166e',
    messagingSenderId: '332757779499',
    projectId: 'smartspace-66555',
    storageBucket: 'smartspace-66555.firebasestorage.app',
    iosBundleId: 'com.example.smartspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9vayT4hvqv2fky7iT8NC0nUcJzuwxU7w',
    appId: '1:332757779499:ios:682ae09c7c5646cb1c166e',
    messagingSenderId: '332757779499',
    projectId: 'smartspace-66555',
    storageBucket: 'smartspace-66555.firebasestorage.app',
    iosBundleId: 'com.example.smartspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi3PskP4rkmjaETTu0hipcILh27wWhsgA',
    appId: '1:332757779499:web:da5138f86ff025c31c166e',
    messagingSenderId: '332757779499',
    projectId: 'smartspace-66555',
    authDomain: 'smartspace-66555.firebaseapp.com',
    storageBucket: 'smartspace-66555.firebasestorage.app',
  );
}
