import 'dart:io' show Platform;
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:smartspace/seller/noticications_screen.dart';
import 'firebase_options.dart';
import 'buyer/buyer_home_screen.dart';
// This file is generated by `flutterfire configure`

import 'package:smartspace/auth/login_screen.dart';

import 'package:smartspace/seller/my_listings_screen.dart';
import 'package:smartspace/seller/add_listing_screen.dart';
import 'package:smartspace/seller/ai_valuation.dart';
import 'package:smartspace/seller/analytics_screen.dart';

//import 'package:smartspace/seller/mylistings_screen.dart';


void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ✅ Initialize Firebase only on supported platforms
  if (kIsWeb || !(Platform.isWindows || Platform.isLinux || Platform.isMacOS)) {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } else {
    debugPrint("🚫 Firebase initialization skipped on unsupported platform: ${Platform.operatingSystem}");
  }

  runApp(const SmartSpace());
}

class SmartSpace extends StatelessWidget {
  const SmartSpace({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: const LoginScreen(),
      routes: {

        '/mylistings_screen': (context) => const MyListingsScreen(),
        '/buyer_home_screen': (context) => const BuyerHomeScreen(),
        
        '/login_screen': (context) => const LoginScreen(),

       // '/mylistings_screen': (context) => MylistingsScreen(),
        '/analytics_screen': (context) => AnalyticsScreen(),
        '/ai_valuation': (context) => AiValuationScreen(),
        '/notifications_screen': (context) => NoticicationsScreen(),
        '/add_listing_screen': (context) => AddListingScreen(),

      },
    );
  }
}

